import Head from "next/head";
import Link from "next/link";
import Seat from "../../components/Seats";
import styles from "../../styles/Home.module.css";

export default function Reservation() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kinoreservationssystem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Link href="/login">
            <a className={styles.LoginLink}>anmelden</a>
          </Link>
        </div>
        <h1 className={styles.title}>Reservation</h1>
        <p className={styles.description}>Sitzplätze auswählen</p>
        <div className="flex">
          <Seat seatNumber={1} />
          <Seat seatNumber={2} />
          <Seat seatNumber={3} />
          <Seat seatNumber={4} />
          <Seat seatNumber={5} />
          <Seat seatNumber={6} />
          <Seat seatNumber={7} />
          <Seat seatNumber={8} />
        </div>

        <div className="flex">
          <Seat seatNumber={9} />
          <Seat seatNumber={10} />
          <Seat seatNumber={11} />
          <Seat seatNumber={12} />
          <Seat seatNumber={13} />
          <Seat seatNumber={14} />
        </div>

        <div className="flex">
          <Seat seatNumber={15} />
          <Seat seatNumber={16} />
          <Seat seatNumber={17} />
          <Seat seatNumber={18} />
        </div>

        <Link href="/commit">
          <a>
            <button className="SubmitButton border border-black rounded p-2 w-32 bg-gradient-to-r from-blue-600 to-blue-800 text-white mt-4">
              Reservieren
            </button>
          </a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Hatice & Luca
          <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
}
