import react, { useEffect } from "react";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import confetti from "https://cdn.skypack.dev/canvas-confetti";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kinoreservationssystem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Link href="/login">
            <a className={styles.LoginLink}>anmelden</a>
          </Link>
        </div>
        <h1 className={styles.title}>Cinema</h1>
        <p className={styles.description}>
          <Link href="/films">
            <a>
              <button
                className="SubmitButton border border-black rounded p-2 w-32 bg-gradient-to-r from-blue-600 to-blue-800 text-white"
                onClick={() => confetti()}
              >Filme</button>
            </a>
          </Link>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Hatice & Luca
          <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
}
