import Card from "../../components/Card";
import FilmMenu from "../../components/FilmMenu";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Films.module.css";

const Films = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kinoreservationssystem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-blue-600 w-full h-52">
        <div className="ml-10 pt-10">
          <Link href="/">
            <a className={styles.title}>Cinema.</a>
          </Link>
        </div>
        <div className="pt-14 mr-96 text-gray-300 font-bold ml-10 flex justify-between w-auto">
          <FilmMenu link="/films?beliebt" txt={"Beliebt"}/>
          <FilmMenu link="/films?action" txt={"Action"}/>
          <FilmMenu link="/films?horror" txt={"Horror"}/>
          <FilmMenu link="/films?komedy" txt={"Komödie"}/>
          <FilmMenu link="/films?drama" txt={"Drama"}/>
          <FilmMenu link="/films?love" txt={"Liebe"}/>
        </div>
      </div>

      <main className={styles.main}>
        <div>
          <Link href="/login">
            <a className={styles.LoginLink}>anmelden</a>
          </Link>
        </div>

        <div className={styles.grid}>
          <Card
            src={"/spiderman.webp"}
            alt="spiderman"
            title="No way home"
            txt="BatmanBatmanBatman"
          />
          <Card
            src={"/spiderman.webp"}
            alt="spiderman"
            title="No way home"
            txt="BatmanBatmanBatman"
          />
          <Card
            src={"/spiderman.webp"}
            alt="spiderman"
            title="No way home"
            txt="BatmanBatmanBatman"
          />
          <Card
            src={"/spiderman.webp"}
            alt="spiderman"
            title="No way home"
            txt="BatmanBatmanBatman"
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Hatice & Luca
          <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
};

export default Films;
